# Docker compose for setting up a local development environment
version: '3.7'

services:
  database-service:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - backend-network
  user-service:
    image: user-service
    build:
      context: user/
      dockerfile: Dockerfile
    ports:
      - 50051:50051
      - 8080:8080
    depends_on:
      - database-service
    environment:
      - DB_HOST=database-service
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - JWT_SECRET=Thisisajwtsecret
      - JWT_EXPIRY=48
      - GRPC_HOST=user-service
      - GRPC_PORT=50051
      - HTTP_HOST=user-service
      - HTTP_PORT=8080
      - LOG_LEVEL=debug
    networks:
      - backend-network
  video-service:
    image: video-service
    build:
      context: video/
      dockerfile: Dockerfile
    ports:
      - 50052:50052
    depends_on:
      - database-service
    environment:
      - DB_HOST=database-service
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - SERVER_HOST=video-service
      - SERVER_PORT=50052
      - LOG_LEVEL=debug
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
      